import type { LabourTruthItem } from "./labour-truth-types";

export const labourTruthData: LabourTruthItem[] = [
  {
    id: "LT-001", product: "HBM Charme XL", dept: "hand",
    w_apu: 185, o_apu: 220, c_apu: 210, p_apu: 200, apu: 205,
    stelen_per_persoon_per_uur: 185, arbeid_per_stuk: 0.32,
    assessment: "likely_undercharged", confidence: 0.88,
    reason: "W-APU (185) ligt 16% onder O-APU (220). Klant betaalt voor hogere productiviteit dan gerealiseerd.",
    recommendation: "Herbereken O-APU op basis van recente W-APU metingen. Overweeg prijscorrectie of receptvereenvoudiging.",
    labor_source: "HBM Productie Checks", calculation_method: "W-APU / O-APU ratio-analyse",
    period: "Week 10–12 2026", updated_at: "2026-03-17T08:00:00Z",
  },
  {
    id: "LT-002", product: "HBM Trend", dept: "band",
    w_apu: 340, o_apu: 330, c_apu: 355, p_apu: 335, apu: 338,
    stelen_per_persoon_per_uur: 340, arbeid_per_stuk: 0.18,
    assessment: "aligned", confidence: 0.92,
    reason: "W-APU (340) ligt dicht bij O-APU (330) en P-APU (335). Arbeidslast correct doorbelast.",
    recommendation: "Geen actie vereist. Monitoren op seizoenseffecten.",
    labor_source: "HBM Productie Checks", calculation_method: "W-APU / O-APU ratio-analyse",
    period: "Week 10–12 2026", updated_at: "2026-03-17T08:00:00Z",
  },
  {
    id: "LT-003", product: "HBM De Luxe", dept: "hand",
    w_apu: 165, o_apu: 180, c_apu: 195, p_apu: 175, apu: 180,
    stelen_per_persoon_per_uur: 165, arbeid_per_stuk: 0.36,
    assessment: "likely_undercharged", confidence: 0.84,
    reason: "W-APU (165) ligt 8% onder O-APU (180). Complexiteit recept hoger dan doorberekend.",
    recommendation: "Receptanalyse uitvoeren. Overweeg componentvereenvoudiging of O-APU correctie.",
    labor_source: "HBM Productie Checks", calculation_method: "W-APU / O-APU ratio-analyse",
    period: "Week 10–12 2026", updated_at: "2026-03-17T08:00:00Z",
  },
  {
    id: "LT-004", product: "HBM Lovely", dept: "band",
    w_apu: 365, o_apu: 330, c_apu: 350, p_apu: 340, apu: 345,
    stelen_per_persoon_per_uur: 365, arbeid_per_stuk: 0.16,
    assessment: "likely_overcharged", confidence: 0.79,
    reason: "W-APU (365) ligt 11% boven O-APU (330). Klant betaalt voor lagere productiviteit dan gerealiseerd.",
    recommendation: "Overweeg O-APU update naar realistische waarde. Kan concurrentievoordeel opleveren.",
    labor_source: "HBM Productie Checks", calculation_method: "W-APU / O-APU ratio-analyse",
    period: "Week 10–12 2026", updated_at: "2026-03-17T08:00:00Z",
  },
  {
    id: "LT-005", product: "HBM Field M", dept: "hand",
    w_apu: 195, o_apu: 210, c_apu: 220, p_apu: 205, apu: 210,
    stelen_per_persoon_per_uur: 195, arbeid_per_stuk: 0.31,
    assessment: "needs_review", confidence: 0.62,
    reason: "W-APU (195) toont hoge variatie tussen metingen. Onvoldoende data voor betrouwbare conclusie.",
    recommendation: "Extra meetreeks plannen. Minimaal 10 extra checks vereist voor betrouwbare beoordeling.",
    labor_source: "HBM Productie Checks", calculation_method: "W-APU / O-APU ratio-analyse",
    period: "Week 10–12 2026", updated_at: "2026-03-17T08:00:00Z",
  },
  {
    id: "LT-006", product: "HBM Elegance", dept: "hand",
    w_apu: 175, o_apu: 200, c_apu: 205, p_apu: 190, apu: 195,
    stelen_per_persoon_per_uur: 175, arbeid_per_stuk: 0.34,
    assessment: "likely_undercharged", confidence: 0.86,
    reason: "W-APU (175) ligt 13% onder O-APU (200). Significante mismatch tussen doorbelasting en werkelijkheid.",
    recommendation: "Prioriteit: herbereken O-APU. Impact geschat op €1.200/maand bij correctie.",
    labor_source: "HBM Productie Checks", calculation_method: "W-APU / O-APU ratio-analyse",
    period: "Week 10–12 2026", updated_at: "2026-03-17T08:00:00Z",
  },
];
