/* Single source of truth for Kanban cards — consumed by KanbanBoard + MCAgenda */

import type { KanbanCard } from "./kanban-shared";

const initialCards: KanbanCard[] = [
  // Development tasks
  { id: "1",  title: "BQ Trend voorbereiden",        description: "Alle materialen klaarzetten en receptuur controleren voor start productie.", category: "productie", priority: "high",   labels: ["urgent", "lijn-1"],     status: "todo",        task_type: "development", dueDate: "28 feb", startTime: "07:00", stopTime: "09:30", createdAt: "26 feb", agent: "ProductieAgent", recurring: true, recurrence_pattern: "daily", recurrence_label: "Dagelijkse productie prep", next_run_at: "Morgen 07:00", last_run_at: "Vandaag 07:00" },
  { id: "2",  title: "Bezetting middag plannen",      description: "Shift 2 bezetting afstemmen met beschikbare medewerkers.",                  category: "planning",  priority: "medium", labels: ["shift-2"],              status: "todo",        task_type: "development", startTime: "12:00", stopTime: "13:00", createdAt: "27 feb" },
  { id: "8",  title: "Nieuwe medewerker inwerken",    description: "Onboarding programma doorlopen met nieuwe medewerker op lijn 2.",           category: "personeel", priority: "low",    labels: ["onboarding"],           status: "todo",        task_type: "development", assignee: "Maria", startTime: "09:00", stopTime: "17:00", createdAt: "25 feb" },
  { id: "11", title: "Verpakkingsmateriaal bestellen", description: "Voorraad dozen en sleeves aanvullen voor volgende week.",                  category: "logistiek", priority: "medium", labels: ["voorraad"],             status: "todo",        task_type: "development", createdAt: "27 feb", agent: "LogistiekAgent", recurring: true, recurrence_pattern: "weekly", recurrence_label: "Wekelijkse voorraadcheck", next_run_at: "Maandag 08:00", last_run_at: "Vorige week ma" },
  { id: "3",  title: "BQ Field L produceren",         description: "Lopende productie op lijn 2, target 180 stuks.",                            category: "productie", priority: "high",   labels: ["lijn-2", "actief"],     status: "in_progress", task_type: "development", assignee: "Jan",    dueDate: "28 feb", startTime: "06:30", stopTime: "14:00", createdAt: "28 feb", overnight_flag: true, last_activity_at: "Vandaag 06:12", overnight_summary: "Forecast engine afgerond, wacht op Axerrio feed", overnight_activity_log: [
    { timestamp: "06:12", description: "Completed forecast engine integration" },
    { timestamp: "04:48", description: "Updated Marktmonitor adapter" },
    { timestamp: "02:15", description: "Detected missing Axerrio feed" },
  ] },
  { id: "5",  title: "Koelcel voorraad tellen",       description: "Inventarisatie koelcel 1 en 2 voor planning morgen.",                       category: "koelcel",   priority: "medium", labels: ["inventaris"],           status: "in_progress", task_type: "development", startTime: "15:00", stopTime: "16:00", createdAt: "28 feb", overnight_flag: true, last_activity_at: "Vandaag 03:30", overnight_summary: "Temperatuurlog bijgewerkt vanuit sensor data", overnight_activity_log: [
    { timestamp: "03:30", description: "Temperatuurlog koelcel 1 & 2 automatisch bijgewerkt" },
    { timestamp: "01:10", description: "Sensor calibratie check uitgevoerd" },
  ], recurring: true, recurrence_pattern: "daily", recurrence_label: "Dagelijkse inventarisatie", next_run_at: "Morgen 15:00", last_run_at: "Vandaag 15:00" },
  { id: "12", title: "Temperatuur koelcel 3 checken", description: "Melding ontvangen van temperatuurafwijking, handmatige controle nodig.",    category: "koelcel",   priority: "high",   labels: ["urgent", "melding"],    status: "in_progress", task_type: "development", assignee: "Pieter", startTime: "09:15", createdAt: "28 feb" },
  { id: "10", title: "Transport schema bevestigen",   description: "Ochtendroute bevestigen met transporteur en laadtijden doorgeven.",         category: "logistiek", priority: "high",   labels: ["ochtend"],              status: "review",      task_type: "development", assignee: "Pieter", dueDate: "28 feb", startTime: "05:30", stopTime: "06:00", createdAt: "27 feb", recurring: true, recurrence_pattern: "daily", recurrence_label: "Dagelijks transport", next_run_at: "Morgen 05:30", last_run_at: "Vandaag 05:30" },
  { id: "6",  title: "BQ de Luxe afgerond",           description: "Productie succesvol afgerond. 195/200 boeketten goedgekeurd.",              category: "productie", priority: "medium", labels: ["lijn-1", "✓"],          status: "done",        task_type: "development", assignee: "Jan", startTime: "06:30", stopTime: "12:00", createdAt: "27 feb" },
  { id: "7",  title: "BQ Chique afgerond",            description: "Batch compleet, 100% goedgekeurd.",                                        category: "productie", priority: "low",    labels: ["lijn-3", "✓"],          status: "done",        task_type: "development", startTime: "07:00", stopTime: "11:30", createdAt: "26 feb" },
  { id: "14", title: "Weekplanning week 10",          description: "Planning voor volgende week afgerond en gecommuniceerd.",                   category: "planning",  priority: "medium", labels: ["planning", "✓"],        status: "done",        task_type: "development", assignee: "Maria", startTime: "08:00", stopTime: "10:00", createdAt: "26 feb" },

  // Analysis tasks
  { id: "4",  title: "BQ Elegance kwaliteitscheck",   description: "Steekproef van 20 boeketten controleren op kwaliteitsnormen.",              category: "qc",        priority: "medium", labels: ["steekproef"],           status: "in_progress", task_type: "analysis", assignee: "Lisa", analysis_kind: "quality", analysis_status: "running", methodiek_name: "HBM Productanalyse", methodiek_id: "prod-efficiency", methodiek_version: "v3.2", result_ready_flag: false, createdAt: "28 feb", overnight_flag: true, last_activity_at: "Vandaag 05:44", overnight_summary: "Steekproef data automatisch verwerkt, 3 resultaten klaar", overnight_activity_log: [
    { timestamp: "05:44", description: "Steekproef resultaten van lijn 1 verwerkt" },
    { timestamp: "04:12", description: "Automatische kwaliteitsscan afgerond" },
    { timestamp: "03:00", description: "Nachtelijke batch controle gestart" },
  ], recurring: true, recurrence_pattern: "daily", recurrence_label: "Dagelijkse QC check", next_run_at: "Morgen 06:00", last_run_at: "Vandaag 05:44" },
  { id: "9",  title: "BQ Lovely verpakkingcheck",     description: "Verpakking en etikettering controleren voor verzending.",                   category: "qc",        priority: "low",    labels: ["verpakking"],           status: "review",      task_type: "analysis", analysis_kind: "quality", analysis_status: "completed", methodiek_name: "HBM Productanalyse", methodiek_id: "prod-efficiency", methodiek_version: "v3.2", result_ready_flag: true, result_summary: "18/20 boeketten goedgekeurd. 2 afwijkingen op etikettering geconstateerd.", result_payload: "Steekproef van 20 boeketten uitgevoerd.\n\n**Resultaten:**\n- 18 boeketten voldoen aan alle kwaliteitsnormen\n- 2 boeketten hebben afwijkende etikettering (verkeerde barcode positie)\n- Bloem kwaliteit: 100% goedgekeurd\n- Verpakking integriteit: 100% goedgekeurd\n\n**Aanbeveling:** Etiketteermachine op lijn 3 laten herkalibreren.", result_updated_at: "28 feb 14:30", createdAt: "27 feb", run_history: [
    { run_id: "run-9a", methodiek_version: "v3.2", analysis_status: "completed", result_summary: "18/20 boeketten goedgekeurd. 2 afwijkingen op etikettering.", data_scope: "Batch BQ-Lovely-2802", created_at: "28 feb 14:30" },
    { run_id: "run-9b", methodiek_version: "v3.1", analysis_status: "completed", result_summary: "15/20 boeketten goedgekeurd. 5 afwijkingen (3 etikettering, 2 verpakking).", data_scope: "Batch BQ-Lovely-2702", created_at: "27 feb 11:00" },
  ] },
  { id: "13", title: "Productie rapport ochtend",     description: "Samenvatting ochtendproductie verzenden naar management.",                  category: "planning",  priority: "medium", labels: ["rapport"],              status: "review",      task_type: "analysis", assignee: "Lisa", analysis_kind: "production", analysis_status: "completed", methodiek_name: "HBM Productie Rapportage", methodiek_id: "cost-per-stem", methodiek_version: "v2.1", result_ready_flag: true, result_summary: "Ochtendproductie 94% van target. Lijn 2 lichte vertraging door materiaal tekort.", result_payload: "**Productie Rapport — Ochtend 28 feb**\n\nLijn 1: 98 stuks (target 100) — 98%\nLijn 2: 85 stuks (target 100) — 85%\nLijn 3: 95 stuks (target 100) — 95%\n\nTotaal: 278/300 = 92.7%\n\n**Issues:**\n- Lijn 2: 15 min vertraging door late levering groenmateriaal\n- Koelcel 3: temperatuurmelding om 09:15, handmatig gecontroleerd\n\n**Acties:**\n- Materiaal leverancier gecontacteerd voor middag\n- Extra koelcel controle ingepland", result_updated_at: "28 feb 12:15", createdAt: "28 feb", run_history: [
    { run_id: "run-13a", methodiek_version: "v2.1", analysis_status: "completed", result_summary: "Ochtendproductie 94% van target.", data_scope: "Ochtendshift 28 feb", created_at: "28 feb 12:15" },
    { run_id: "run-13b", methodiek_version: "v2.1", analysis_status: "completed", result_summary: "Ochtendproductie 97% van target.", data_scope: "Ochtendshift 27 feb", created_at: "27 feb 12:10" },
    { run_id: "run-13c", methodiek_version: "v2.0", analysis_status: "completed", result_summary: "Ochtendproductie 91% van target.", data_scope: "Ochtendshift 26 feb", created_at: "26 feb 12:20" },
  ], recurring: true, recurrence_pattern: "daily", recurrence_label: "Dagelijks ochtendrapport", next_run_at: "Morgen 12:00", last_run_at: "Vandaag 12:15" },
  { id: "15", title: "Marge-analyse week 9",          description: "Wekelijkse marge-analyse per productlijn uitvoeren.",                       category: "planning",  priority: "high",   labels: ["financieel"],           status: "todo",        task_type: "analysis", analysis_kind: "margin", analysis_status: "pending", methodiek_name: "HBM Marge Intelligence", methodiek_id: "cost-per-stem", methodiek_version: "v2.1", result_ready_flag: false, createdAt: "28 feb", recurring: true, recurrence_pattern: "weekly", recurrence_label: "Wekelijkse marge-analyse", next_run_at: "Maandag 08:00", last_run_at: "Vorige week ma" },
  { id: "16", title: "Inkoopprijs benchmark rozen",   description: "Vergelijking inkoopprijs rozen met marktgemiddelde afgelopen 4 weken.",     category: "logistiek", priority: "medium", labels: ["inkoop"],               status: "in_progress", task_type: "analysis", assignee: "Jan", analysis_kind: "procurement", analysis_status: "running", methodiek_name: "ERP Mapping Reverse Engineer", methodiek_id: "erp-mapping", methodiek_version: "v1.3", result_ready_flag: false, createdAt: "27 feb", recurring: true, recurrence_pattern: "monthly", recurrence_label: "Maandelijkse benchmark", next_run_at: "1 apr", last_run_at: "1 mrt" },
  { id: "17", title: "Logistieke route optimalisatie", description: "Analyse van huidige routes vs alternatieven voor kostenbesparing.",         category: "logistiek", priority: "low",    labels: ["optimalisatie"],        status: "todo",        task_type: "analysis", analysis_kind: "logistics", analysis_status: "blocked", methodiek_name: "HBM Logistiek Analyse", methodiek_id: "route-optimization", methodiek_version: "v1.8", result_ready_flag: false, result_summary: "Geblokkeerd: wachtend op GPS data export van transporteur.", createdAt: "25 feb" },
  { id: "18", title: "Receptuur mapping alle lijnen",  description: "Volledige mapping van recepturen naar ERP structuur.",                      category: "productie", priority: "high",   labels: ["mapping", "erp"],       status: "in_progress", task_type: "analysis", assignee: "Pieter", analysis_kind: "mapping", analysis_status: "stale", methodiek_name: "ERP Mapping Reverse Engineer", methodiek_id: "erp-mapping", methodiek_version: "v1.3", result_ready_flag: true, result_summary: "Mapping chain confirmed through SalesOrder → ProductionOrder → Invoice. 3 orphan recipes gevonden.", result_payload: "**ERP Mapping Analyse**\n\nMapping chain: SalesOrder → ProductionOrder → Invoice ✓\n\n**Gevonden orphan recipes:**\n1. RCP-2024-089 (BQ Seasonal Mix)\n2. RCP-2024-112 (BQ Premium Rose)\n3. RCP-2024-145 (BQ Garden Special)\n\n**Status:** Laatste update 5 dagen geleden — mogelijk verouderd.", result_updated_at: "12 mrt 09:00", createdAt: "10 mrt", run_history: [
    { run_id: "run-18a", methodiek_version: "v1.3", analysis_status: "stale", result_summary: "Mapping chain confirmed. 3 orphan recipes gevonden.", data_scope: "Alle productlijnen", created_at: "12 mrt 09:00" },
    { run_id: "run-18b", methodiek_version: "v1.2", analysis_status: "completed", result_summary: "Mapping chain confirmed. 1 orphan recipe gevonden.", data_scope: "Lijn 1-3", created_at: "5 mrt 14:00" },
  ] },
];

export const getKanbanCards = (): KanbanCard[] => initialCards;

export default initialCards;
