import type { FloritrackData } from "./floritrack-types";

export const FLORITRACK_MOCK: FloritrackData = {
  summary: {
    total: 13,
    purchased: 9,
    inTransit: 3,
    delivered: 1,
    lastUpdated: "2026-03-18T06:44:16",
  },
  transactions: [
    {
      id: "1619",
      status: "Aangekocht",
      article: "CHR S AAA INSTA",
      articleCode: "126038",
      location: "FloraHolland Aalsmeer (Klok)",
      purchaseTime: "06:44:16",
      transactionNumber: "1619",
      content: 75,
      quantity: { delivered: 0, total: 30 },
      remark: "",
      seat: "6597",
      clock: "11",
      buyer: "Bl.grth. Anton van der Hoorn BV (423178)",
      place: "647",
      supplier: "van Helvoort Company (8662)",
      packaging: "544",
      batchSequenceNumber: "000267",
      destination: "Rozenburg / Hoorn Bloommasters",
      currentLocation: "Vestiging: KLOK FLORAHOLLAND AALSMEER",
      lastUpdate: "2026-03-18T06:44:16",
      expectedDeliveryTime: "2026-03-18T11:30:00",
      timeline: [
        {
          status: "Aangekocht",
          date: "2026-03-18",
          time: "06:44:16",
          location: "Vestiging: KLOK FLORAHOLLAND AALSMEER, Legmeerdijk 313, 1431 GB Aalsmeer",
          unit: "",
          vehicle: "",
        },
      ],
    },
    {
      id: "1620",
      status: "Onderweg",
      article: "ROS R 60 REDNAOMI",
      articleCode: "204512",
      location: "FloraHolland Naaldwijk",
      purchaseTime: "05:32:10",
      transactionNumber: "1620",
      content: 120,
      quantity: { delivered: 0, total: 50 },
      remark: "Spoed levering",
      seat: "4210",
      clock: "07",
      buyer: "Bl.grth. Anton van der Hoorn BV (423178)",
      place: "312",
      supplier: "De Ruiter Roses (3421)",
      packaging: "612",
      batchSequenceNumber: "000342",
      destination: "Rozenburg / Hoorn Bloommasters",
      currentLocation: "In transit - A4 richting Hoorn",
      lastUpdate: "2026-03-18T08:15:00",
      timeline: [
        {
          status: "Aangekocht",
          date: "2026-03-18",
          time: "05:32:10",
          location: "FloraHolland Naaldwijk, Middelbroekweg 29",
          unit: "Kar-14",
          vehicle: "",
        },
        {
          status: "Onderweg",
          date: "2026-03-18",
          time: "07:45:00",
          location: "Vertrek FloraHolland Naaldwijk",
          unit: "Kar-14",
          vehicle: "Vrachtwagen BT-412-X",
        },
      ],
    },
    {
      id: "1621",
      status: "Afgeleverd",
      article: "TUL W 40 WHITEPR",
      articleCode: "310287",
      location: "FloraHolland Rijnsburg",
      purchaseTime: "04:18:55",
      transactionNumber: "1621",
      content: 200,
      quantity: { delivered: 40, total: 40 },
      remark: "",
      seat: "1105",
      clock: "03",
      buyer: "Bl.grth. Anton van der Hoorn BV (423178)",
      place: "108",
      supplier: "Borst Bloembollen (1287)",
      packaging: "320",
      batchSequenceNumber: "000118",
      destination: "Rozenburg / Hoorn Bloommasters",
      currentLocation: "Bloommasters Hoorn - Magazijn",
      lastUpdate: "2026-03-18T09:22:00",
      timeline: [
        {
          status: "Aangekocht",
          date: "2026-03-18",
          time: "04:18:55",
          location: "FloraHolland Rijnsburg, Leidsevaart 520",
          unit: "Kar-07",
          vehicle: "",
        },
        {
          status: "Onderweg",
          date: "2026-03-18",
          time: "06:00:00",
          location: "Vertrek FloraHolland Rijnsburg",
          unit: "Kar-07",
          vehicle: "Vrachtwagen NL-88-ZK",
        },
        {
          status: "Afgeleverd",
          date: "2026-03-18",
          time: "09:22:00",
          location: "Bloommasters Hoorn, Industrieweg 12",
          unit: "Kar-07",
          vehicle: "Vrachtwagen NL-88-ZK",
        },
      ],
    },
    {
      id: "1622",
      status: "Onderweg",
      article: "GER M MIX GARDEN",
      articleCode: "415903",
      location: "FloraHolland Aalsmeer (Klok)",
      purchaseTime: "06:12:30",
      transactionNumber: "1622",
      content: 60,
      quantity: { delivered: 0, total: 20 },
      remark: "",
      seat: "6597",
      clock: "11",
      buyer: "Bl.grth. Anton van der Hoorn BV (423178)",
      place: "647",
      supplier: "Könst Alstroemeria (5540)",
      packaging: "410",
      batchSequenceNumber: "000289",
      destination: "Rozenburg / Hoorn Bloommasters",
      currentLocation: "In transit - vertrokken Aalsmeer",
      lastUpdate: "2026-03-18T07:50:00",
      timeline: [
        {
          status: "Aangekocht",
          date: "2026-03-18",
          time: "06:12:30",
          location: "FloraHolland Aalsmeer, Legmeerdijk 313",
          unit: "Kar-22",
          vehicle: "",
        },
        {
          status: "Onderweg",
          date: "2026-03-18",
          time: "07:50:00",
          location: "Vertrek FloraHolland Aalsmeer",
          unit: "Kar-22",
          vehicle: "Vrachtwagen BX-190-D",
        },
      ],
    },
    {
      id: "1623",
      status: "Aangekocht",
      article: "LIS O 50 ASIATIC",
      articleCode: "508712",
      location: "FloraHolland Aalsmeer (Klok)",
      purchaseTime: "06:50:02",
      transactionNumber: "1623",
      content: 40,
      quantity: { delivered: 0, total: 10 },
      remark: "Kwaliteit A+",
      seat: "6597",
      clock: "11",
      buyer: "Bl.grth. Anton van der Hoorn BV (423178)",
      place: "647",
      supplier: "Vletter & Den Haan (2190)",
      packaging: "280",
      batchSequenceNumber: "000301",
      destination: "Rozenburg / Hoorn Bloommasters",
      currentLocation: "Vestiging: KLOK FLORAHOLLAND AALSMEER",
      lastUpdate: "2026-03-18T06:50:02",
      timeline: [
        {
          status: "Aangekocht",
          date: "2026-03-18",
          time: "06:50:02",
          location: "FloraHolland Aalsmeer, Legmeerdijk 313",
          unit: "",
          vehicle: "",
        },
      ],
    },
  ],
};
