import type { ActionItem } from "./types";

export const actionItems: ActionItem[] = [
  {
    id: "act-001",
    action_title: "Optimize Band Line B3",
    department_owner: "Productie",
    sub_department: "Band",
    driver: "line_efficiency",
    recommended_action: "Review staffing configuration and adjust APU baseline on B3 line.",
    expected_impact: "+3 W-APU / €1,050 per week",
    effort_level: "Medium",
    priority: "Critical",
    status: "in_progress",
    probability: 0.85,
    impact_financial: 54600,
    impact_efficiency: 3.0,
    impact_risk_reduction: "low",
    data_sources_used: ["HBM Production", "Axerrio DW"],
    source_signal: "Production Intelligence – Line B3 underperformance",
  },
  {
    id: "act-002",
    action_title: "Secure Germini Franky supply",
    department_owner: "Inkoop",
    driver: "forecast_gap",
    flower: "Germini Franky",
    recommended_action: "Secure 45,000 stems before week 38 via preferred supplier.",
    expected_impact: "+1.2% margin improvement",
    effort_level: "Low",
    priority: "High",
    status: "open",
    probability: 0.9,
    impact_financial: 28800,
    impact_supply_stability: 12,
    impact_risk_reduction: "medium",
    data_sources_used: ["HBM Production", "Picklist", "Axerrio DW"],
    source_signal: "Procurement Intelligence – Supply gap detected",
    constraints: "Maintain orange color palette",
  },
  {
    id: "act-003",
    action_title: "Increase price BQ Fleur",
    department_owner: "Verkoop",
    driver: "margin_gap",
    flower: "BQ Fleur",
    recommended_action: "Verhoog verkoopprijs met €0.05 richting Vomar.",
    expected_impact: "+0.8% marge-verbetering",
    effort_level: "Low",
    priority: "High",
    status: "open",
    probability: 0.75,
    impact_financial: 19200,
    impact_risk_reduction: "none",
    data_sources_used: ["Axerrio DW", "Picklist"],
    source_signal: "Margin Intelligence – BQ Fleur below target",
  },
  {
    id: "act-004",
    action_title: "Optimize bouquet recipe Charme XL",
    department_owner: "Productie",
    sub_department: "Hand",
    driver: "design_efficiency",
    flower: "Boeket Charme XL",
    recommended_action: "Vervang Alstroemeria door Chrysant – 18% snellere productie.",
    expected_impact: "−€0.006 arbeid/bos",
    effort_level: "Medium",
    priority: "Medium",
    status: "open",
    probability: 0.8,
    impact_financial: 14400,
    impact_efficiency: 1.2,
    impact_risk_reduction: "none",
    constraints: "Kleurpalet behouden",
    data_sources_used: ["Picklist", "HBM Production"],
    source_signal: "Production Intelligence – Recipe optimization",
  },
  {
    id: "act-005",
    action_title: "Plan extra weekend shift W39",
    department_owner: "Productie",
    sub_department: "Band",
    driver: "demand_surge",
    recommended_action: "Plan zaterdagshift voor week 39 – orders 14% boven forecast.",
    expected_impact: "+4,200 extra boeketten",
    effort_level: "High",
    priority: "High",
    status: "in_progress",
    probability: 0.7,
    impact_financial: 12600,
    impact_efficiency: 2.3,
    impact_risk_reduction: "low",
    constraints: "Personeelsbeschikbaarheid",
    data_sources_used: ["HBM Production", "Axerrio DW"],
    source_signal: "Flower Forecast – Demand spike week 39",
  },
  {
    id: "act-006",
    action_title: "Extend tulip contract volume",
    department_owner: "Inkoop",
    driver: "supply_risk",
    flower: "Tulp Premium Mix",
    recommended_action: "Verleng contractvolume met 20,000 stelen voor Q4.",
    expected_impact: "Leveringszekerheid +15%",
    effort_level: "Medium",
    priority: "Medium",
    status: "open",
    probability: 0.65,
    impact_financial: 9600,
    impact_supply_stability: 15,
    impact_risk_reduction: "medium",
    data_sources_used: ["Picklist", "Axerrio DW"],
    source_signal: "Risk Radar – Tulip supply fragility",
  },
  {
    id: "act-007",
    action_title: "Monitor rose quality KE-2024-0834",
    department_owner: "Inkoop",
    driver: "quality_signal",
    flower: "Roos Avalanche 60cm",
    recommended_action: "Track uitval% komende 3 leveringen partij KE-2024-0834.",
    expected_impact: "Preventie afkeur −2%",
    effort_level: "Low",
    priority: "Low",
    status: "open",
    probability: 0.5,
    impact_financial: 4800,
    impact_risk_reduction: "low",
    data_sources_used: ["HBM Production"],
    source_signal: "Risk Radar – Quality degradation signal",
  },
  {
    id: "act-008",
    action_title: "Shift BQ Elegance to B3",
    department_owner: "Productie",
    sub_department: "Band",
    driver: "production_efficiency",
    recommended_action: "Verplaats BQ Elegance naar lijn B3 (350 st/u) voor hogere output.",
    expected_impact: "+€2.1K/week extra output",
    effort_level: "Medium",
    priority: "High",
    status: "in_progress",
    probability: 0.8,
    impact_financial: 21600,
    impact_efficiency: 2.1,
    impact_risk_reduction: "none",
    constraints: "B3 capaciteit max 8 uur/dag",
    data_sources_used: ["HBM Production"],
    source_signal: "Production Intelligence – Output optimization",
  },
  {
    id: "act-009",
    action_title: "Reduce packaging waste Inpak",
    department_owner: "Productie",
    sub_department: "Inpak",
    driver: "waste_reduction",
    recommended_action: "Switch naar smaller sleeve formaat voor single-stem producten.",
    expected_impact: "−12% verpakkingskosten",
    effort_level: "Low",
    priority: "Medium",
    status: "completed",
    probability: 0.9,
    impact_financial: 7200,
    impact_risk_reduction: "none",
    data_sources_used: ["HBM Production"],
    source_signal: "Profit Engine – Cost leakage analysis",
  },
  {
    id: "act-010",
    action_title: "Negotiate Kenya freight rate",
    department_owner: "Inkoop",
    driver: "cost_optimization",
    recommended_action: "Heronderhandel vrachtkosten met KQ Cargo voor Q4 volume.",
    expected_impact: "−€0.008/stem freight cost",
    effort_level: "High",
    priority: "Medium",
    status: "open",
    probability: 0.55,
    impact_financial: 9600,
    impact_risk_reduction: "low",
    impact_supply_stability: 5,
    data_sources_used: ["Axerrio DW"],
    source_signal: "Procurement Intelligence – Freight cost trend",
  },
  {
    id: "act-011",
    action_title: "Automate Koelcel temperature alerts",
    department_owner: "Productie",
    sub_department: "Koelcel",
    driver: "quality_control",
    recommended_action: "Implementeer automatische alerts bij temp > 4°C langer dan 30 min.",
    expected_impact: "−3% uitval door temperatuur",
    effort_level: "Medium",
    priority: "Medium",
    status: "completed",
    probability: 0.85,
    impact_financial: 8400,
    impact_risk_reduction: "high",
    data_sources_used: ["HBM Production"],
    source_signal: "Risk Radar – Cold chain monitoring",
  },
  {
    id: "act-012",
    action_title: "Cross-sell premium mix to Action",
    department_owner: "Verkoop",
    driver: "revenue_growth",
    flower: "Premium Seasonal Mix",
    recommended_action: "Bied premium mix aan bij Action voor testperiode van 4 weken.",
    expected_impact: "+€3.200/maand extra omzet",
    effort_level: "Medium",
    priority: "Low",
    status: "open",
    probability: 0.4,
    impact_financial: 3200,
    impact_risk_reduction: "none",
    data_sources_used: ["Axerrio DW"],
    source_signal: "Chance Radar – New channel opportunity",
  },
  /* ── Procurement Forecast Actions ── */
  {
    id: "act-013",
    action_title: "Koppel ontbrekende recepten top-5 klanten",
    department_owner: "Productie",
    sub_department: "Hand",
    driver: "recipe_resolution",
    recommended_action: "Prioriteer receptkoppeling voor 149 onopgeloste orders. Start met AH, Jumbo en REWE programma's.",
    expected_impact: "Forecast dekking +40%",
    effort_level: "Medium",
    priority: "Critical",
    status: "open",
    probability: 0.9,
    impact_financial: 0,
    impact_risk_reduction: "high",
    data_sources_used: ["HBM Production", "Picklist"],
    source_signal: "Forecast Intelligence – Unresolved recipe blocker",
    constraints: "Receptdesign team capaciteit",
  },
  {
    id: "act-014",
    action_title: "Beveilig leveranciersvolume Wk 14-16",
    department_owner: "Inkoop",
    driver: "supply_security",
    flower: "Diverse",
    recommended_action: "Beveilig volume bij top-3 leveranciers voor piekweken op basis van beschikbare forecastdata.",
    expected_impact: "Leveringszekerheid +20%",
    effort_level: "Medium",
    priority: "High",
    status: "open",
    probability: 0.7,
    impact_financial: 15000,
    impact_supply_stability: 20,
    impact_risk_reduction: "high",
    data_sources_used: ["Picklist", "HBM Production"],
    source_signal: "Procurement Forecast Risk – Supply coverage onbekend",
  },
  {
    id: "act-015",
    action_title: "Verifieer forecast aannames seizoenswisseling",
    department_owner: "Verkoop",
    driver: "forecast_validation",
    recommended_action: "Review forecast aannames voor lente/zomer overgang. Valideer met actuele ordertrend van afgelopen 4 weken.",
    expected_impact: "Forecast betrouwbaarheid +15%",
    effort_level: "Low",
    priority: "High",
    status: "open",
    probability: 0.8,
    impact_financial: 8000,
    impact_risk_reduction: "medium",
    data_sources_used: ["HBM Production", "Axerrio DW"],
    source_signal: "Forecast Intelligence – Forecast reliability concern",
  },
  {
    id: "act-016",
    action_title: "Onderzoek productidentiteit onbekende items",
    department_owner: "Productie",
    driver: "product_identity",
    recommended_action: "Identificeer en koppel 25 orders met onbekende productidentiteit (placeholder-gebruik). Escaleer naar productdesign.",
    expected_impact: "Recipe coverage +17%",
    effort_level: "Low",
    priority: "Medium",
    status: "open",
    probability: 0.85,
    impact_financial: 0,
    impact_risk_reduction: "medium",
    data_sources_used: ["HBM Production"],
    source_signal: "Unresolved Recipe Panel – Placeholder products",
  },
  {
    id: "act-017",
    action_title: "Vul ontbrekende inkoopprijzen aan",
    department_owner: "Inkoop",
    driver: "price_completion",
    recommended_action: "Werk actuele inkoopprijzen bij voor 38% van de artikelen die alleen offerteprijzen hebben. Prioriteer hoog-volume bloemen.",
    expected_impact: "Inkoopwaarde berekening +38%",
    effort_level: "Medium",
    priority: "High",
    status: "open",
    probability: 0.75,
    impact_financial: 12000,
    impact_risk_reduction: "medium",
    data_sources_used: ["Picklist", "Axerrio DW"],
    source_signal: "Procurement Forecast – Missing price data",
  },
  {
    id: "act-018",
    action_title: "Escaleer vraagconcentratie Moederdag",
    department_owner: "Verkoop",
    driver: "demand_concentration",
    recommended_action: "Moederdag orders concentreren 45% van weekvolume op 2 dagen. Coördineer met productie en inkoop voor capaciteitsplanning.",
    expected_impact: "Leverbetrouwbaarheid +25%",
    effort_level: "High",
    priority: "High",
    status: "open",
    probability: 0.65,
    impact_financial: 20000,
    impact_risk_reduction: "high",
    constraints: "Afhankelijk van productieplanning en personeelsinzet",
    data_sources_used: ["HBM Production", "Axerrio DW"],
    source_signal: "Chance Radar – Demand concentration signal",
  },
];
