import type { OpsIntelligenceData } from "./operations-types";

export const OPS_MOCK: OpsIntelligenceData = {
  date: "2026-03-18",
  summary: {
    totalShipments: 6,
    loadUnits: 14,
    shipmentsByStatus: { Gepland: 1, Geladen: 1, Onderweg: 2, Afgeleverd: 1, Afwijking: 1 },
    totalTransactions: 18,
    packagingUnits: 42,
    transactionsByStatus: { Aangekocht: 5, Inslag: 3, Onderweg: 6, Afgeleverd: 4 },
    activeVehicles: 3,
    delayedShipments: 2,
    deviationCount: 3,
    productionAtRisk: 3,
    bouquetsAtRisk: 85,
  },
  shipments: [
    {
      id: "Z-001",
      status: "Afgeleverd",
      time: "06:15",
      client: "Albert Heijn DC Zaandam",
      location: "FloraHolland Rijnsburg",
      loadUnit: "3 karren",
      logisticsProvider: "Van Vliet Transport",
      label: "AH-ZDM-0318",
      plate: "NL-88-ZK",
      vehicleStatus: "afgerond",
      deviation: "ok",
      transactions: [
        {
          id: "T-1001",
          status: "Afgeleverd",
          article: "TUL W 40 WHITEPR",
          articleCode: "310287",
          quantity: { delivered: 40, total: 40 },
          content: 200,
          clock: "03",
          buyer: "Anton van der Hoorn BV",
          supplier: "Borst Bloembollen (1287)",
          packaging: "320",
          brief: "AH-ZDM-0318-A",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "04:18:55", location: "FloraHolland Rijnsburg", unit: "Kar-07", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "05:40:00", location: "FloraHolland Rijnsburg – Dock 3", unit: "Kar-07", vehicle: "" },
            { status: "Onderweg", date: "2026-03-18", time: "06:00:00", location: "Vertrek Rijnsburg", unit: "Kar-07", vehicle: "Vrachtwagen NL-88-ZK" },
            { status: "Afgeleverd", date: "2026-03-18", time: "09:22:00", location: "HBM Rozenburg – Magazijn", unit: "Kar-07", vehicle: "Vrachtwagen NL-88-ZK" },
          ],
        },
        {
          id: "T-1002",
          status: "Afgeleverd",
          article: "ROS P 50 AVALANCHE",
          articleCode: "204100",
          quantity: { delivered: 30, total: 30 },
          content: 150,
          clock: "03",
          buyer: "Anton van der Hoorn BV",
          supplier: "Dümmen Orange (4412)",
          packaging: "210",
          brief: "AH-ZDM-0318-B",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "04:30:12", location: "FloraHolland Rijnsburg", unit: "Kar-07", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "05:42:00", location: "FloraHolland Rijnsburg – Dock 3", unit: "Kar-07", vehicle: "" },
            { status: "Onderweg", date: "2026-03-18", time: "06:00:00", location: "Vertrek Rijnsburg", unit: "Kar-07", vehicle: "Vrachtwagen NL-88-ZK" },
            { status: "Afgeleverd", date: "2026-03-18", time: "09:22:00", location: "HBM Rozenburg – Magazijn", unit: "Kar-07", vehicle: "Vrachtwagen NL-88-ZK" },
          ],
        },
      ],
    },
    {
      id: "Z-002",
      status: "Onderweg",
      time: "07:45",
      client: "Jumbo DC Veghel",
      location: "FloraHolland Naaldwijk",
      loadUnit: "2 karren",
      logisticsProvider: "Floriway Logistics",
      label: "JMB-VGL-0318",
      plate: "BT-412-X",
      vehicleStatus: "actief",
      deviation: "warning",
      deviationMessage: "15 min vertraagd – file A4 Leidschendam",
      transactions: [
        {
          id: "T-1003",
          status: "Onderweg",
          article: "ROS R 60 REDNAOMI",
          articleCode: "204512",
          quantity: { delivered: 0, total: 50 },
          content: 120,
          clock: "07",
          buyer: "Anton van der Hoorn BV",
          supplier: "De Ruiter Roses (3421)",
          packaging: "612",
          brief: "JMB-VGL-0318-A",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "05:32:10", location: "FloraHolland Naaldwijk", unit: "Kar-14", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "06:50:00", location: "FloraHolland Naaldwijk – Dock 7", unit: "Kar-14", vehicle: "" },
            { status: "Onderweg", date: "2026-03-18", time: "07:45:00", location: "Vertrek Naaldwijk", unit: "Kar-14", vehicle: "Vrachtwagen BT-412-X" },
          ],
          productionRisk: "high",
          productionRiskMessage: "Vertraagd – 50 stelen nodig voor 3 productie-orders die om 12:00 vertrekken",
          bouquetAllocations: [
            { bouquetName: "Lovely", quantity: 20, productionOrder: "PO-2841", departureTime: "12:00", departureDate: "2026-03-18", customer: "Jumbo" },
            { bouquetName: "De Luxe", quantity: 15, productionOrder: "PO-2843", departureTime: "12:00", departureDate: "2026-03-18", customer: "Jumbo" },
            { bouquetName: "Trend", quantity: 15, productionOrder: "PO-2850", departureTime: "14:00", departureDate: "2026-03-18", customer: "Jumbo" },
          ],
        },
        {
          id: "T-1004",
          status: "Onderweg",
          article: "CHR S AAA INSTA",
          articleCode: "126038",
          quantity: { delivered: 0, total: 30 },
          content: 75,
          clock: "07",
          buyer: "Anton van der Hoorn BV",
          supplier: "van Helvoort Company (8662)",
          packaging: "544",
          brief: "JMB-VGL-0318-B",
          deviation: { type: "incomplete", message: "24/30 beschikbaar op moment van laden" },
          productionRisk: "medium",
          productionRiskMessage: "6 stelen tekort – productie-order PO-2844 kan vertraagd raken",
          bouquetAllocations: [
            { bouquetName: "Charme XL", quantity: 20, productionOrder: "PO-2844", departureTime: "14:00", departureDate: "2026-03-18", customer: "Jumbo" },
            { bouquetName: "Elegance", quantity: 10, productionOrder: "PO-2846", departureTime: "15:30", departureDate: "2026-03-18", customer: "Jumbo" },
          ],
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "05:48:30", location: "FloraHolland Naaldwijk", unit: "Kar-14", vehicle: "" },
            { status: "Onderweg", date: "2026-03-18", time: "07:45:00", location: "Vertrek Naaldwijk", unit: "Kar-14", vehicle: "Vrachtwagen BT-412-X" },
          ],
        },
      ],
    },
    {
      id: "Z-003",
      status: "Geladen",
      time: "08:30",
      client: "Lidl DC Heerenveen",
      location: "FloraHolland Aalsmeer",
      loadUnit: "4 karren",
      logisticsProvider: "BloemTransport Nederland",
      label: "LDL-HRV-0318",
      plate: "BX-190-D",
      vehicleStatus: "actief",
      deviation: "ok",
      transactions: [
        {
          id: "T-1005",
          status: "Inslag",
          article: "GER M MIX GARDEN",
          articleCode: "415903",
          quantity: { delivered: 0, total: 20 },
          content: 60,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "Könst Alstroemeria (5540)",
          packaging: "410",
          brief: "LDL-HRV-0318-A",
          bouquetAllocations: [
            { bouquetName: "Spring Bouquet", quantity: 12, productionOrder: "PO-2860", departureTime: "16:00", departureDate: "2026-03-18", customer: "Lidl" },
            { bouquetName: "Field M", quantity: 8, productionOrder: "PO-2861", departureTime: "16:00", departureDate: "2026-03-18", customer: "Lidl" },
          ],
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "06:12:30", location: "FloraHolland Aalsmeer", unit: "Kar-22", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "08:10:00", location: "FloraHolland Aalsmeer – Dock 12", unit: "Kar-22", vehicle: "" },
          ],
        },
        {
          id: "T-1006",
          status: "Aangekocht",
          article: "LIS O 50 ASIATIC",
          articleCode: "508712",
          quantity: { delivered: 0, total: 10 },
          content: 40,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "Vletter & Den Haan (2190)",
          packaging: "280",
          brief: "LDL-HRV-0318-B",
          deviation: { type: "missing_scan", message: "Inslag scan ontbreekt" },
          productionRisk: "high",
          productionRiskMessage: "Scan ontbreekt – 10 stelen nodig voor PO-2862, vertrek 13:00",
          bouquetAllocations: [
            { bouquetName: "Chique", quantity: 10, productionOrder: "PO-2862", departureTime: "13:00", departureDate: "2026-03-18", customer: "Lidl" },
          ],
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "06:50:02", location: "FloraHolland Aalsmeer", unit: "", vehicle: "" },
          ],
        },
        {
          id: "T-1007",
          status: "Inslag",
          article: "HYA B 30 DELFTBL",
          articleCode: "612044",
          quantity: { delivered: 0, total: 15 },
          content: 90,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "Jan de Wit & Zonen (3210)",
          packaging: "180",
          brief: "LDL-HRV-0318-C",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "06:55:00", location: "FloraHolland Aalsmeer", unit: "Kar-22", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "08:15:00", location: "FloraHolland Aalsmeer – Dock 12", unit: "Kar-22", vehicle: "" },
          ],
        },
      ],
    },
    {
      id: "Z-004",
      status: "Onderweg",
      time: "09:10",
      client: "PLUS DC Haarlemmermeer",
      location: "FloraHolland Aalsmeer",
      loadUnit: "2 karren",
      logisticsProvider: "Van Vliet Transport",
      label: "PLS-HLM-0318",
      plate: "5154",
      vehicleStatus: "actief",
      deviation: "ok",
      transactions: [
        {
          id: "T-1008",
          status: "Onderweg",
          article: "FRE Y 40 SUNBEAU",
          articleCode: "720130",
          quantity: { delivered: 0, total: 25 },
          content: 100,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "Fides B.V. (6780)",
          packaging: "350",
          brief: "PLS-HLM-0318-A",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "06:20:00", location: "FloraHolland Aalsmeer", unit: "Kar-31", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "07:55:00", location: "FloraHolland Aalsmeer – Dock 5", unit: "Kar-31", vehicle: "" },
            { status: "Onderweg", date: "2026-03-18", time: "09:10:00", location: "Vertrek Aalsmeer", unit: "Kar-31", vehicle: "Vrachtwagen 5154" },
          ],
        },
        {
          id: "T-1009",
          status: "Onderweg",
          article: "ANE R 35 CORONAR",
          articleCode: "830044",
          quantity: { delivered: 0, total: 18 },
          content: 54,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "Bieze Stadskanaal (2310)",
          packaging: "162",
          brief: "PLS-HLM-0318-B",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "06:35:00", location: "FloraHolland Aalsmeer", unit: "Kar-31", vehicle: "" },
            { status: "Inslag", date: "2026-03-18", time: "08:00:00", location: "FloraHolland Aalsmeer – Dock 5", unit: "Kar-31", vehicle: "" },
            { status: "Onderweg", date: "2026-03-18", time: "09:10:00", location: "Vertrek Aalsmeer", unit: "Kar-31", vehicle: "Vrachtwagen 5154" },
          ],
        },
      ],
    },
    {
      id: "Z-005",
      status: "Afwijking",
      time: "07:00",
      client: "Aldi DC Groenlo",
      location: "FloraHolland Naaldwijk",
      loadUnit: "1 kar",
      logisticsProvider: "Floriway Logistics",
      label: "ALD-GRL-0318",
      deviation: "critical",
      deviationMessage: "Zending geblokkeerd – kwaliteitscontrole afgekeurd",
      transactions: [
        {
          id: "T-1010",
          status: "Aangekocht",
          article: "ROS W 50 AKITO",
          articleCode: "204890",
          quantity: { delivered: 0, total: 20 },
          content: 100,
          clock: "07",
          buyer: "Anton van der Hoorn BV",
          supplier: "Kordes Roses (1190)",
          packaging: "200",
          brief: "ALD-GRL-0318-A",
          deviation: { type: "stuck", message: "Status niet veranderd sinds 07:00" },
          productionRisk: "high",
          productionRiskMessage: "Geblokkeerd – 20 stelen nodig voor PO-2870, vertrek 11:00 vandaag",
          bouquetAllocations: [
            { bouquetName: "Lovely", quantity: 20, productionOrder: "PO-2870", departureTime: "11:00", departureDate: "2026-03-18", customer: "Aldi" },
          ],
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "05:10:00", location: "FloraHolland Naaldwijk", unit: "Kar-09", vehicle: "" },
          ],
        },
      ],
    },
    {
      id: "Z-006",
      status: "Gepland",
      time: "12:00",
      client: "Dekamarkt DC Velsen",
      location: "FloraHolland Aalsmeer",
      loadUnit: "2 karren",
      logisticsProvider: "BloemTransport Nederland",
      label: "DKM-VLS-0318",
      deviation: "ok",
      transactions: [
        {
          id: "T-1011",
          status: "Aangekocht",
          article: "PIV M MIX PASTEL",
          articleCode: "920044",
          quantity: { delivered: 0, total: 35 },
          content: 140,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "Zentoo (8810)",
          packaging: "490",
          brief: "DKM-VLS-0318-A",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "06:58:00", location: "FloraHolland Aalsmeer", unit: "", vehicle: "" },
          ],
        },
        {
          id: "T-1012",
          status: "Aangekocht",
          article: "EUS P 60 LISIALA",
          articleCode: "530088",
          quantity: { delivered: 0, total: 12 },
          content: 48,
          clock: "11",
          buyer: "Anton van der Hoorn BV",
          supplier: "van den Berg Roses (4590)",
          packaging: "144",
          brief: "DKM-VLS-0318-B",
          timeline: [
            { status: "Aangekocht", date: "2026-03-18", time: "07:02:00", location: "FloraHolland Aalsmeer", unit: "", vehicle: "" },
          ],
        },
      ],
    },
  ],
  vehicleFlows: [
    {
      plate: "NL-88-ZK",
      status: "afgerond",
      events: [
        { time: "06:00", status: "Vertrek", location: "FloraHolland Rijnsburg", shipmentId: "Z-001" },
        { time: "07:45", status: "Checkpoint A4", location: "Knooppunt Burgerveen" },
        { time: "09:22", status: "Afgeleverd", location: "HBM Rozenburg", shipmentId: "Z-001" },
      ],
    },
    {
      plate: "BT-412-X",
      status: "actief",
      events: [
        { time: "07:45", status: "Vertrek", location: "FloraHolland Naaldwijk", shipmentId: "Z-002" },
        { time: "08:30", status: "Checkpoint", location: "A4 Leidschendam" },
        { time: "09:15", status: "Vertraagd", location: "File A4 Leidschendam", shipmentId: "Z-002" },
      ],
    },
    {
      plate: "5154",
      status: "actief",
      events: [
        { time: "09:10", status: "Vertrek", location: "FloraHolland Aalsmeer", shipmentId: "Z-004" },
        { time: "09:58", status: "Checkpoint", location: "A7 Purmerend" },
      ],
    },
  ],
};
