import type { ExecutionIntent } from "./execution-types";

export const executionIntents: ExecutionIntent[] = [
  {
    id: "EX-001",
    action_type: "Leverancierswitch",
    recommended_action: "Switch rozen-inkoop van Van Dijk naar FloraConnect voor week 13–16 op basis van betere prijs/kwaliteit-ratio.",
    priority: "high",
    urgency_score: 82,
    confidence: 0.87,
    execution_status: "proposed",
    execution_mode: "semi-auto",
    owner: "Inkoop",
    due_date: "2026-03-20",
    source_type: "procurement",
    source_context: "Procurement Intelligence — prijsvergelijking rozen Q1",
    created_at: "2026-03-15T09:22:00Z",
    reasoning: "FloraConnect biedt 12% lagere stemprijs bij vergelijkbare kwaliteitsscores (8.1 vs 7.9). Historisch betrouwbare levering (98.5% on-time). Marge-impact geschat op +€2.400/maand.",
    execution_payload: { supplier_from: "Van Dijk Roses", supplier_to: "FloraConnect BV", stems_per_week: 12000, price_delta: -0.12 },
    risk_level: "medium",
    risk_type: "Leveranciersafhankelijkheid",
    related_task_ids: ["KAN-042"],
  },
  {
    id: "EX-002",
    action_type: "Receptaanpassing",
    recommended_action: "Vervang Lisianthus door Chrysant in HBM Trend recept — beschikbaarheid Lisianthus daalt seizoensmatig.",
    priority: "medium",
    urgency_score: 65,
    confidence: 0.74,
    execution_status: "approved",
    execution_mode: "semi-auto",
    owner: "Productie",
    due_date: "2026-03-19",
    source_type: "production",
    source_context: "Recept Intelligence — beschikbaarheidsanalyse week 12",
    created_at: "2026-03-14T14:10:00Z",
    reasoning: "Lisianthus beschikbaarheid daalt naar 40% in week 13. Chrysant biedt vergelijkbaar kleurprofiel en is 94% beschikbaar. Klantacceptatie verwacht op basis van vergelijkbare composities in 2025.",
    execution_payload: { recipe: "HBM Trend", remove: "Lisianthus", add: "Chrysant", stems_delta: 0 },
    risk_level: "low",
  },
  {
    id: "EX-003",
    action_type: "Prijsaanpassing",
    recommended_action: "Verhoog verkoopprijs HBM De Luxe met €0.50 — marktprijs stijgt en marge is onder target.",
    priority: "high",
    urgency_score: 78,
    confidence: 0.81,
    execution_status: "prepared",
    execution_mode: "semi-auto",
    owner: "Commercieel",
    due_date: "2026-03-18",
    source_type: "commercial",
    source_context: "Marge Intelligence — De Luxe margeanalyse",
    created_at: "2026-03-13T11:30:00Z",
    updated_at: "2026-03-16T08:00:00Z",
    reasoning: "Huidige marge 18% vs. target 24%. Marktprijs is +8% gestegen in afgelopen 4 weken. Prijselasticiteit analyse toont minimaal volume-effect bij €0.50 verhoging.",
    execution_payload: { product: "HBM De Luxe", current_price: 12.50, new_price: 13.00, margin_impact: "+4.8%" },
    risk_level: "medium",
    risk_type: "Volume-effect",
    related_task_ids: ["KAN-038"],
  },
  {
    id: "EX-004",
    action_type: "Voorraadcorrectie",
    recommended_action: "Verhoog tulpen-bestelling week 13 met 20% — Moederdag-forecast toont piekverbruik.",
    priority: "critical",
    urgency_score: 91,
    confidence: 0.92,
    execution_status: "in_progress",
    execution_mode: "semi-auto",
    owner: "Inkoop",
    due_date: "2026-03-17",
    source_type: "forecast",
    source_context: "Flower Forecast — Moederdag piekanalyse",
    created_at: "2026-03-12T16:00:00Z",
    updated_at: "2026-03-17T07:15:00Z",
    reasoning: "Forecast model voorspelt 35% hogere tulpen-vraag in week 13–14. Historische data Moederdag 2024/2025 bevestigt patroon. Vroeg bestellen voorkomt spotmarkt-toeslag.",
    execution_payload: { flower: "Tulpen", current_order: 8000, new_order: 9600, supplier: "Dutch Tulip Co" },
    risk_level: "low",
  },
  {
    id: "EX-005",
    action_type: "Lijnherschikking",
    recommended_action: "Verplaats HBM Lovely productie van Lijn 2 naar Lijn 3 — betere throughput verwacht.",
    priority: "medium",
    urgency_score: 55,
    confidence: 0.68,
    execution_status: "completed",
    execution_mode: "manual",
    owner: "Productie",
    source_type: "production",
    source_context: "Production Efficiency — lijnbezettingsanalyse",
    created_at: "2026-03-10T10:00:00Z",
    updated_at: "2026-03-15T16:30:00Z",
    reasoning: "Lijn 3 toont 12% hogere stems/uur voor vergelijkbare composities. Verplaatsing bespaart geschat 45 min per dagrun.",
    risk_level: "low",
  },
  {
    id: "EX-006",
    action_type: "Kwaliteitsalert",
    recommended_action: "Pauzeer inkoop bij leverancier MegaFlora — 3 opeenvolgende batches onder kwaliteitsnorm.",
    priority: "high",
    urgency_score: 85,
    confidence: 0.90,
    execution_status: "failed",
    execution_mode: "semi-auto",
    owner: "Inkoop",
    source_type: "sentinel",
    source_context: "Sentinel — kwaliteitsmonitoring leveranciers",
    created_at: "2026-03-11T08:45:00Z",
    updated_at: "2026-03-16T14:00:00Z",
    reasoning: "Kwaliteitsscores MegaFlora: 5.2, 4.8, 5.1 (norm: 7.0). Klachtenpercentage gestegen naar 8%. Automatische pauzering gefaald door ontbrekende API-koppeling.",
    failure_reason: "Leveranciers-API koppeling niet actief. Handmatige actie vereist via CRM.",
    execution_payload: { supplier: "MegaFlora BV", quality_scores: [5.2, 4.8, 5.1], threshold: 7.0 },
    risk_level: "high",
    risk_type: "Kwaliteitsrisico",
  },
  {
    id: "EX-007",
    action_type: "Contractverlenging",
    recommended_action: "Verleng seizoenscontract met Kenya Bloom voor Q2 — gunstige condities aangeboden.",
    priority: "low",
    urgency_score: 40,
    confidence: 0.72,
    execution_status: "cancelled",
    execution_mode: "manual",
    owner: "Inkoop",
    source_type: "strategic-insight",
    source_context: "Strategic Insight — leveranciersportfolio Q2",
    created_at: "2026-03-09T13:00:00Z",
    updated_at: "2026-03-14T09:00:00Z",
    reasoning: "Kenya Bloom biedt 5% korting bij vroegtijdige verlenging. Echter, interne beslissing om Kenya-import tijdelijk te pauzeren maakt dit niet relevant.",
    risk_level: "low",
  },
  {
    id: "EX-008",
    action_type: "Marktanalyse",
    recommended_action: "Activeer uitgebreide marktprijsmonitoring voor zonnebloemen — prijsvolatiliteit neemt toe.",
    priority: "medium",
    urgency_score: 58,
    confidence: 0.65,
    execution_status: "rejected",
    execution_mode: "auto",
    owner: "Data Team",
    source_type: "strategic-insight",
    source_context: "Market Intelligence — volatiliteitsdetectie",
    created_at: "2026-03-08T10:30:00Z",
    reasoning: "Zonnebloem-prijzen tonen 22% hogere volatiliteit dan gemiddelde. Echter, volume is beperkt en monitoring-overhead wordt niet gerechtvaardigd door potentiële impact.",
    risk_level: "low",
  },
];
