import type { PricingIntent, InventoryRiskIntent } from "./pricing-inventory-types";

export const pricingIntents: PricingIntent[] = [
  {
    id: "PR-001",
    product_name: "HBM De Luxe",
    advised_price_action: "increase",
    current_price: 12.50,
    proposed_delta_value: 0.50,
    proposed_delta_pct: 4.0,
    urgency_score: 78,
    confidence: 0.81,
    reason: "Marge 18% vs. target 24%. Marktprijs +8% in 4 weken. Concurrenten verhogen eveneens.",
    recommendation: "Verhoog verkoopprijs met €0,50 naar €13,00. Geschatte marge-impact: +4.8%.",
    execution_status: "proposed",
    execution_mode: "semi-auto",
    priority: "high",
    owner: "Commercieel",
    due_date: "2026-03-18",
    source_type: "commercial",
    source_context: "Marge Intelligence — De Luxe margeanalyse",
    source_rule_id: "RULE-PRICE-MARGIN-GAP",
    risk_level: "medium",
    created_at: "2026-03-15T11:30:00Z",
    execution_payload: { product: "HBM De Luxe", current: 12.50, proposed: 13.00, margin_current: "18%", margin_target: "24%" },
  },
  {
    id: "PR-002",
    product_name: "HBM Charme XL",
    advised_price_action: "review",
    current_price: 14.80,
    urgency_score: 62,
    confidence: 0.65,
    reason: "W-APU (185) wijkt sterk af van O-APU (220). Arbeidskosten hoger dan doorberekend.",
    recommendation: "Review nodig: kostprijsherberekening op basis van actuele W-APU voor correcte doorbelasting.",
    execution_status: "proposed",
    execution_mode: "semi-auto",
    priority: "medium",
    owner: "Commercieel",
    source_type: "production",
    source_context: "Labour Truth — Charme XL APU-mismatch",
    source_rule_id: "RULE-PRICE-LABOUR-MISMATCH",
    risk_level: "medium",
    created_at: "2026-03-16T09:00:00Z",
    related_task_ids: ["LT-001"],
  },
  {
    id: "PR-003",
    product_name: "HBM Trend",
    advised_price_action: "hold",
    current_price: 9.90,
    urgency_score: 25,
    confidence: 0.92,
    reason: "Marge op target (23.5%), APU aligned, marktprijs stabiel.",
    recommendation: "Geen actie vereist. Prijs en marge in lijn met doelstellingen.",
    execution_status: "approved",
    execution_mode: "semi-auto",
    priority: "low",
    owner: "Commercieel",
    source_type: "commercial",
    source_context: "Marge Intelligence — wekelijkse prijscheck",
    source_rule_id: "RULE-PRICE-STABLE",
    risk_level: "low",
    created_at: "2026-03-14T14:00:00Z",
  },
  {
    id: "PR-004",
    product_name: "HBM Lovely",
    advised_price_action: "decrease",
    current_price: 11.20,
    proposed_delta_value: -0.30,
    proposed_delta_pct: -2.7,
    urgency_score: 45,
    confidence: 0.79,
    reason: "W-APU (365) overtreft O-APU (330) met 11%. Klant betaalt meer arbeid dan werkelijk nodig.",
    recommendation: "Overweeg prijsverlaging van €0,30 voor concurrentievoordeel. Marge blijft boven target.",
    execution_status: "proposed",
    execution_mode: "semi-auto",
    priority: "low",
    owner: "Commercieel",
    source_type: "production",
    source_context: "Labour Truth — Lovely overperformance",
    source_rule_id: "RULE-PRICE-OVERCHARGED",
    risk_level: "low",
    created_at: "2026-03-16T10:00:00Z",
    related_task_ids: ["LT-004"],
  },
];

export const inventoryRiskIntents: InventoryRiskIntent[] = [
  {
    id: "INV-001",
    product_name: "Tulpen (mix)",
    risk_type: "undersupply",
    severity: "critical",
    recommended_action: "Verhoog tulpen-bestelling week 13 met 20% — Moederdag-forecast toont piekverbruik.",
    urgency_score: 91,
    confidence: 0.92,
    reason: "Forecast voorspelt 35% hogere vraag week 13–14. Huidige bestelling dekt slechts 72% van verwachte behoefte.",
    execution_status: "in_progress",
    execution_mode: "semi-auto",
    priority: "critical",
    owner: "Inkoop",
    due_date: "2026-03-17",
    source_type: "forecast",
    source_context: "Flower Forecast — Moederdag piekanalyse",
    source_rule_id: "RULE-INV-FORECAST-GAP",
    risk_level: "high",
    created_at: "2026-03-12T16:00:00Z",
    updated_at: "2026-03-17T07:15:00Z",
    execution_payload: { flower: "Tulpen", current_order: 8000, recommended: 9600, coverage_current: "72%", coverage_target: "95%" },
  },
  {
    id: "INV-002",
    product_name: "Lisianthus",
    risk_type: "undersupply",
    severity: "high",
    recommended_action: "Activeer substituut (Chrysant) voor HBM Trend recept — beschikbaarheid daalt seizoensmatig naar 40%.",
    urgency_score: 75,
    confidence: 0.82,
    reason: "Beschikbaarheid Lisianthus daalt naar 40% in week 13. Zonder substituut is productie HBM Trend in gevaar.",
    execution_status: "approved",
    execution_mode: "semi-auto",
    priority: "high",
    owner: "Inkoop",
    due_date: "2026-03-19",
    source_type: "procurement",
    source_context: "Beschikbaarheidsmonitor — seizoensanalyse week 12",
    source_rule_id: "RULE-INV-AVAILABILITY-DROP",
    risk_level: "high",
    created_at: "2026-03-14T08:00:00Z",
    execution_payload: { flower: "Lisianthus", availability: "40%", substitute: "Chrysant", substitute_availability: "94%" },
    related_task_ids: ["EX-002"],
  },
  {
    id: "INV-003",
    product_name: "Rozen (rood, 60cm)",
    risk_type: "oversupply",
    severity: "medium",
    recommended_action: "Verlaag rozen-bestelling week 14 met 15% — vraagprognose toont daling na Moederdag.",
    urgency_score: 52,
    confidence: 0.76,
    reason: "Forecast toont 20% vraagdaling week 15. Bij ongewijzigde bestelling ontstaat overvoorraad van ~2.400 stelen.",
    execution_status: "proposed",
    execution_mode: "semi-auto",
    priority: "medium",
    owner: "Inkoop",
    due_date: "2026-03-21",
    source_type: "forecast",
    source_context: "Flower Forecast — post-Moederdag correctie",
    source_rule_id: "RULE-INV-OVERSUPPLY-FORECAST",
    risk_level: "medium",
    created_at: "2026-03-16T11:00:00Z",
    execution_payload: { flower: "Rozen rood 60cm", current_order: 16000, recommended: 13600, excess_risk: "2.400 stelen" },
  },
  {
    id: "INV-004",
    product_name: "Gerbera (geel)",
    risk_type: "stale_stock",
    severity: "high",
    recommended_action: "Verwerk restvoorraad Gerbera geel in aanbiedings-boeketten — houdbaarheid nadert limiet.",
    urgency_score: 82,
    confidence: 0.88,
    reason: "1.200 stelen in koelcel sinds donderdag. Geschatte houdbaarheid: max 48 uur. Derving bij geen actie: €480.",
    execution_status: "proposed",
    execution_mode: "semi-auto",
    priority: "high",
    owner: "Productie",
    due_date: "2026-03-18",
    source_type: "sentinel",
    source_context: "Koelcel monitoring — houdbaarheidsalert",
    source_rule_id: "RULE-INV-STALE-THRESHOLD",
    risk_level: "high",
    created_at: "2026-03-17T06:30:00Z",
    execution_payload: { flower: "Gerbera geel", stock: 1200, days_in_storage: 3, max_days: 5, waste_risk: "€480" },
  },
  {
    id: "INV-005",
    product_name: "Chrysant (wit)",
    risk_type: "margin_pressure",
    severity: "medium",
    recommended_action: "Monitor inkoopprijs Chrysant wit — marktprijs +12% t.o.v. vorige maand. Overweeg alternatieve leverancier.",
    urgency_score: 58,
    confidence: 0.71,
    reason: "Inkoopprijs stijgt terwijl verkoopprijs vast ligt. Marge daalt van 22% naar 16%.",
    execution_status: "proposed",
    execution_mode: "manual",
    priority: "medium",
    owner: "Inkoop",
    source_type: "procurement",
    source_context: "Prijsmonitoring — markttrend chrysanten",
    source_rule_id: "RULE-INV-MARGIN-SQUEEZE",
    risk_level: "medium",
    created_at: "2026-03-15T09:00:00Z",
    execution_payload: { flower: "Chrysant wit", purchase_price_prev: 0.18, purchase_price_now: 0.20, margin_prev: "22%", margin_now: "16%" },
  },
];
